FROM node:18.16.0

# add work dir
RUN mkdir -p /app
WORKDIR /app

# copy dependncy
COPY package.json . 
RUN npm install 

# copy app files 

COPY . .

# host 
EXPOSE 3000

# start app

CMD [ "node", "server.js" ]